---
resources:
  - name: habitat-hello-world-git
    check_every: 1m
    type: git
    source:
      uri: git@github.ford.com:ASALOWI1/habitat-hello-world.git
      branch: master
      private_key: {{private_key}}

jobs:
  - name: asalowi1-habitat-hello-world-linux-pipeline
    public: true
    plan:
      - get: habitat-hello-world-git
      - task: concourse-echo-hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: quay.k8s.ford.com/asalowi1/hab-resource
              tag: latest
              username: {{quay_username}}
              password: {{quay_password}}
          run:
            path: echo
            args: [Hello World!]
...
