---
jobs:
- name: habitat-hello-world-linux
  public: true
  plan:
  - task: habitat-hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{repository}}
          tag: {{tag}}
          username: {{username}}
          password: {{password}}
      run:
        path: echo
        args:
        - hello world
...
